// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecureVoteApp.Data;

#nullable disable

namespace SecureVoteApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311233801_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecureVoteApp.Models.Entities.Candidate", b =>
                {
                    b.Property<Guid>("CandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<Guid>("ConstituencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Party")
                        .HasColumnType("text");

                    b.HasKey("CandidateId");

                    b.HasIndex("ElectionId");

                    b.HasIndex("ConstituencyId", "ElectionId", "FirstName", "LastName")
                        .IsUnique();

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("SecureVoteApp.Models.Entities.Constituency", b =>
                {
                    b.Property<Guid>("ConstituencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalVoters")
                        .HasColumnType("integer");

                    b.HasKey("ConstituencyId");

                    b.ToTable("Constituencies");
                });

            modelBuilder.Entity("SecureVoteApp.Models.Entities.ConstituencyResult", b =>
                {
                    b.Property<Guid>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConstituencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalVotes")
                        .HasColumnType("integer");

                    b.HasKey("ResultId");

                    b.HasIndex("CandidateId");

                    b.HasIndex("ElectionId");

                    b.HasIndex("ConstituencyId", "CandidateId", "ElectionId")
                        .IsUnique();

                    b.ToTable("ConstituencyResults");
                });

            modelBuilder.Entity("SecureVoteApp.Models.Entities.Election", b =>
                {
                    b.Property<Guid>("ElectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ElectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ElectionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ElectionId");

                    b.ToTable("Elections");
                });

            modelBuilder.Entity("SecureVoteApp.Models.Entities.Official", b =>
                {
                    b.Property<Guid>("OfficialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedCountyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedPollingStationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("OfficialId");

                    b.HasIndex("AssignedPollingStationId");

                    b.ToTable("Officials");
                });

            modelBuilder.Entity("SecureVoteApp.Models.Entities.PollingStation", b =>
                {
                    b.Property<Guid>("PollingStationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConstituencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("County")
                        .HasColumnType("text");

                    b.Property<int>("ExpectedVotes")
                        .HasColumnType("integer");

                    b.Property<int>("InvalidVotes")
                        .HasColumnType("integer");

                    b.Property<Guid>("PollingStationCode")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalVotes")
                        .HasColumnType("integer");

                    b.HasKey("PollingStationId");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("PollingStations");
                });

            modelBuilder.Entity("SecureVoteApp.Models.Entities.VoteRecord", b =>
                {
                    b.Property<Guid>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RecordId");

                    b.HasIndex("ElectionId");

                    b.ToTable("VoteRecords");
                });

            modelBuilder.Entity("SecureVoteApp.Models.Entities.Voter", b =>
                {
                    b.Property<Guid>("VoterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConstituencyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ElectoralRollNumber")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("FingerprintScan")
                        .HasColumnType("bytea");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasVoted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WardId")
                        .HasColumnType("uuid");

                    b.HasKey("VoterId");

                    b.HasIndex("ConstituencyId");

                    b.ToTable("Voters");
                });

            modelBuilder.Entity("SecureVoteApp.Models.Entities.Candidate", b =>
                {
                    b.HasOne("SecureVoteApp.Models.Entities.Constituency", "Constituency")
                        .WithMany()
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecureVoteApp.Models.Entities.Election", "Election")
                        .WithMany("Candidates")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");

                    b.Navigation("Election");
                });

            modelBuilder.Entity("SecureVoteApp.Models.Entities.ConstituencyResult", b =>
                {
                    b.HasOne("SecureVoteApp.Models.Entities.Candidate", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecureVoteApp.Models.Entities.Constituency", "Constituency")
                        .WithMany("Results")
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecureVoteApp.Models.Entities.Election", "Election")
                        .WithMany("Results")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Constituency");

                    b.Navigation("Election");
                });

            modelBuilder.Entity("SecureVoteApp.Models.Entities.Official", b =>
                {
                    b.HasOne("SecureVoteApp.Models.Entities.PollingStation", "AssignedPollingStation")
                        .WithMany()
                        .HasForeignKey("AssignedPollingStationId");

                    b.Navigation("AssignedPollingStation");
                });

            modelBuilder.Entity("SecureVoteApp.Models.Entities.PollingStation", b =>
                {
                    b.HasOne("SecureVoteApp.Models.Entities.Constituency", "Constituency")
                        .WithMany("PollingStations")
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("SecureVoteApp.Models.Entities.VoteRecord", b =>
                {
                    b.HasOne("SecureVoteApp.Models.Entities.Election", "Election")
                        .WithMany("VoteRecords")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");
                });

            modelBuilder.Entity("SecureVoteApp.Models.Entities.Voter", b =>
                {
                    b.HasOne("SecureVoteApp.Models.Entities.Constituency", "Constituency")
                        .WithMany("Voters")
                        .HasForeignKey("ConstituencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("SecureVoteApp.Models.Entities.Constituency", b =>
                {
                    b.Navigation("PollingStations");

                    b.Navigation("Results");

                    b.Navigation("Voters");
                });

            modelBuilder.Entity("SecureVoteApp.Models.Entities.Election", b =>
                {
                    b.Navigation("Candidates");

                    b.Navigation("Results");

                    b.Navigation("VoteRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
